version: "3.8"

services:
  postgres_airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"

  warehouse:
    image: postgres:15
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: analytics
    ports:
      - "5433:5432"

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres_airflow
      - warehouse
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "requests pyyaml psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres_airflow
      - warehouse
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "requests pyyaml psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
    command: scheduler
